// import './1.factory';
// import './2.single';
// import './3.prototype';
// import './4.decorator.ts';
// import './5.adapt';
// import './6.proxy';
// import './7.constructorAndstrategy';
// import './8.observer';
// import './9.iterator';
